spring.application.name=booking-service
server.port=8082

spring.datasource.url=jdbc:h2:file:./data/booking-service-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

booking.rabbitmq.exchange=booking.exchange
booking.rabbitmq.queue=booking.queue
booking.rabbitmq.routing-key=booking.routingkey

services.offer-service.base-url=http://localhost:8081
services.user-service.base-url=http://localhost:8080
services.user-service.wallet-balance-path=/user-service-ejb-1.0-SNAPSHOT/api/users/wallet/{userId}
services.user-service.wallet-deduct-path=/user-service-ejb-1.0-SNAPSHOT/api/users/wallet/deduct/{customerId}

jwt.secret=change-this-secret-for-production-user-service
