spring.application.name=offer-service
server.port=8081

spring.datasource.url=jdbc:h2:file:./data/offerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

user.service.jwt.secret=change-this-secret-for-production-user-service

services.booking-service.base-url=http://localhost:8082
services.user-service.base-url=http://localhost:8080
services.user-service.user-details-path=/user-service-ejb-1.0-SNAPSHOT/api/users/{userId}
